#  Provisions a new Webserver

- hosts: localhost
  gather_facts: no
  vars: 
     region: us-west-1
     keypair_name: vijaysmu-keypair
     instance_type: t2.micro
     image_name: ami-056ee704806822732
     ansible_python_interpreter: /usr/bin/python3
     live_ip_address: 54.183.60.183

  tasks:
    - name: Setup Variables for later
      set_fact:
          region: "{{ region }}"
          live_ip_address: "{{ live_ip_address }}"
          ansible_python_interpreter: "{{ ansible_python_interpreter }}"
     
    - name: Ensure botocore and boto3 modules are installed
      pip:
        name:         [ "boto", "botocore"]
        extra_args:   "--user"
  
  tasks:
    - name: Setup security group
      ec2_group:
        name: http-server
        description: Security rules for HTTP Server
        region: "{{ region }}"
        rules_egress:
           - proto: tcp
             from_port: 0
             to_port: 65535
             cidr_ip: 0.0.0.0/0
        rules:
           - proto: tcp
             from_port: 8080
             to_port: 8080
             cidr_ip: 0.0.0.0/0
           
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0

    - name: Provision an instance
      ec2:
        key_name: "{{ keypair_name }}"
        group: http-server
        instance_type: "{{ instance_type }}"
        image: "{{ image_name }}"
        wait: true
        region: "{{region}}"
        exact_count: 1 
        count_tag:
          Name: Webserver
          Deploy: New
        instance_tags:
          Name: Webserver
          Deploy: Blue
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ec2.instances}}"

    - name: Wait for SSH Server to start responding
      wait_for:
              port: 22
              host: "{{item.public_ip}}"
              state: started
      with_items: "{{ec2.instances}}"

- hosts: tag_Deploy_Blue, ec2hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - name: Ensure botocore and boto3 modules are installed
      pip:
        name:         [ "boto", "botocore"]
        extra_args:   "--user"
        
  - name: upgrade all packages
    yum: name=* state=latest
    become: true
  
  - name: Install JDK
    yum:
       name: java-1.8.0-openjdk-devel
       state: latest
    become: true

  - name: Use Java8 for Runtime Java
    alternatives:
       name: java
       path: /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/bin/java
       link: /usr/bin/java
    become: true

  - name: Send the deployment across to the new instance
    copy: 
       src: target/fleetman-0.0.1-SNAPSHOT.war
       dest: /home/ec2-user/webapp/target/
       mode: 0700

  - name: Build a link to the executable so it becomes a service
    file:
            src: /home/ec2-user/webapp/target/fleetman-0.0.1-SNAPSHOT.war
            dest: /etc/init.d/webapp
            state: link
    become: true

  - name: Install Config Server as a startup service
    service:
            name: webapp
            state: started
            enabled: yes
    become: true

  - name: Wait for the new webserver to begin responding
    wait_for:
            host: localhost
            port: 8080
            state: started
            
